# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc04ee8895beedee89272c2eada9e1923d1fabd1fc6bb6bd436ab27b992a98eb0140f311e5bf9e51194975bd1cc1c3650ff4bd91cd6c809757449a8b705e0711

test:
  secret_key_base: 8d9afffebadfc535b88007a9e61b835a8a9ff9ec8eb9687763c18da067909d0e5e20f69d1a80db577116e00aec223e5f2c22ef00fcf85af6836053993fc54d45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
